source 'https://rubygems.org'
ruby '2.5.1'

gem 'capybara', '~> 3.1'
gem 'capybara-screenshot', '~> 1.0', '>= 1.0.21'
gem 'cucumber', '~> 3.1'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'geckodriver-helper', '~> 0.0.5'
gem 'rspec', '~> 3.5'
gem 'selenium-webdriver', '~> 3.12'
gem 'site_prism'